import { heroFields, speakerFields, type PageSpec } from "./types";

/** Home page. Its timeline cards and connector are drawn by `TimelineTrack`. */
export const homePage: PageSpec = {
  slug: "home",
  title: "Home",
  path: "/",
  blocks: [
    {
      key: "home.hero",
      title: "Hero",
      fields: heroFields,
      defaults: {
        heading: "The Biggest and Most Awaited National Entrepreneurship Event",
        description:
          "The 16th UI Studentpreneurs  is The Biggest and Most Awaited National Entrepreneurship event held under Badan Eksekutif Mahasiswa Fakultas Ekonomi dan Bisnis Universitas Indonesia\u201d",
        ctaText: "Register Now",
        ctaLink: "/register",
        image: "/hero.png",
      },
    },
    {
      key: "home.timeline",
      title: "Timeline heading",
      fields: [{ name: "heading", label: "Heading", type: "text" }],
      defaults: { heading: "Our Timeline" },
    },
    {
      key: "home.milestones",
      title: "Milestones heading",
      fields: [{ name: "heading", label: "Heading", type: "text" }],
      defaults: { heading: "Our Milestones" },
    },
    {
      key: "home.speakers",
      title: "Speakers heading",
      fields: [{ name: "heading", label: "Heading", type: "text" }],
      defaults: { heading: "Our Previous Speakers and Assessors" },
    },
  ],
  collections: [
    {
      key: "home.timeline",
      title: "Timeline",
      itemLabel: "Timeline entry",
      fields: [
        { name: "date", label: "Date", type: "text" },
        { name: "title", label: "Title", type: "text" },
      ],
      defaults: [
        { date: "31 Oktober 2026", title: "Grand Opening Webinar" },
        { date: "14 November 2026", title: "Championpreneur Talks" },
        { date: "28 & 30 January 2027", title: "Young Entrepreneur Summit" },
        { date: "17 February 2027", title: "National Seminar" },
        { date: "19 & 20 February 2027", title: "Training and Mentoring" },
        {
          date: "27 February 2027",
          title: "Pitching Day and Awarding Night",
        },
      ],
    },
    {
      key: "home.milestones",
      title: "Milestones",
      itemLabel: "Milestone",
      fields: [
        { name: "image", label: "Illustration", type: "image" },
        { name: "title", label: "Title", type: "text" },
      ],
      defaults: [
        { image: "/milestone1.svg", title: "Grand Opening Webinar" },
        { image: "/milestone2.svg", title: "Championpreneur Talks" },
        { image: "/milestone3.svg", title: "Young Entrepreneur Summit" },
      ],
    },
    {
      key: "home.speakers",
      title: "Speakers and assessors",
      itemLabel: "Person",
      fields: speakerFields,
      defaults: [
        {
          group: "Speakers",
          name: "Alfyn Wendi P.",
          role: "Co-Founder of",
          company: "Republik Investor",
          image: "/speaker1.png",
        },
        {
          group: "Speakers",
          name: "Harwindra Yoga P.",
          role: "E-Commerce Manager of",
          company: "PT Campina Ice Cream Industry Tbk",
          image: "/speaker2.png",
        },
        {
          group: "Speakers",
          name: "Ketty Lie",
          role: "Co-founder of",
          company: "Danacita",
          image: "/speaker3.png",
        },
        {
          group: "Speakers",
          name: "Sandiaga S. Uno",
          role: "Former Minister of",
          company: "Tourism and Creative Economy of Indonesia",
          image: "/speaker4.png",
        },
        {
          group: "Speakers",
          name: "Airyn Tanu",
          role: "Founder & COO of",
          company: "Passion Jewelry Group",
          image: "/speaker5.png",
        },
        {
          group: "Assessors",
          name: "Anindita Nur Annisa",
          role: "Investment Analyst of",
          company: "MDI Ventures",
          image: "/speaker6.png",
        },
        {
          group: "Assessors",
          name: "Maksun Djatmiko",
          role: "Director of",
          company: "Arka Investama Raharja",
          image: "/speaker7.png",
        },
        {
          group: "Assessors",
          name: "Salsabila Firyal Fitri",
          role: "Investments of",
          company: "Telkomsel Ventures",
          image: "/speaker8.png",
        },
      ],
    },
    {
      key: "home.sponsors",
      title: "Sponsors and media partners",
      itemLabel: "Logo",
      fields: [
        {
          name: "group",
          label: "Band",
          type: "text",
          help: "Logos sharing a band scroll together under one heading.",
        },
        { name: "image", label: "Logo", type: "image" },
      ],
      defaults: [
        { group: "Our Sponsor", image: "/sponsor1.png" },
        { group: "Our Sponsor", image: "/sponsor2.png" },
        { group: "Our Sponsor", image: "/sponsor3.png" },
        { group: "Our Sponsor", image: "/sponsor4.png" },
        { group: "Our Sponsor", image: "/sponsor5.png" },
        { group: "Our Sponsor", image: "/sponsor6.png" },
        { group: "Our Sponsor", image: "/sponsor7.png" },
        { group: "Our Media Partner", image: "/medpar1.png" },
        { group: "Our Media Partner", image: "/medpar2.png" },
        { group: "Our Media Partner", image: "/medpar3.png" },
        { group: "Our Media Partner", image: "/medpar4.png" },
        { group: "Our Media Partner", image: "/medpar5.png" },
        { group: "Our Media Partner", image: "/medpar6.png" },
        { group: "Our Media Partner", image: "/medpar7.png" },
        { group: "Our Media Partner", image: "/medpar8.png" },
        { group: "Our Media Partner", image: "/medpar9.png" },
        { group: "Our Media Partner", image: "/medpar10.png" },
        { group: "Our Media Partner", image: "/medpar11.png" },
        { group: "Our Media Partner", image: "/medpar12.png" },
        { group: "Our Media Partner", image: "/medpar13.png" },
        { group: "Our Media Partner", image: "/medpar14.png" },
        { group: "Our Media Partner", image: "/medpar15.png" },
        { group: "Our Media Partner", image: "/medpar16.png" },
        { group: "Our Media Partner", image: "/medpar17.png" },
        { group: "Our Media Partner", image: "/medpar18.png" },
        { group: "Our Media Partner", image: "/medpar19.png" },
        { group: "Our Media Partner", image: "/medpar20.png" },
        { group: "Our Media Partner", image: "/medpar21.png" },
        { group: "Our Media Partner", image: "/medpar22.png" },
        { group: "Our Media Partner", image: "/medpar23.png" },
        { group: "Our Media Partner", image: "/medpar24.png" },
        { group: "Our Media Partner", image: "/medpar25.png" },
        { group: "Our Media Partner", image: "/medpar26.png" },
        { group: "Our Media Partner", image: "/medpar27.png" },
        { group: "Our Media Partner", image: "/medpar28.png" },
        { group: "Our Media Partner", image: "/medpar29.png" },
        { group: "Our Media Partner", image: "/medpar30.png" },
        { group: "Our Media Partner", image: "/medpar31.png" },
        { group: "Our Media Partner", image: "/medpar32.png" },
        { group: "Our Media Partner", image: "/medpar33.png" },
        { group: "Our Media Partner", image: "/medpar34.png" },
        { group: "Our Media Partner", image: "/medpar35.png" },
        { group: "Our Media Partner", image: "/medpar36.png" },
        { group: "Our Media Partner", image: "/medpar37.png" },
        { group: "Our Media Partner", image: "/medpar38.png" },
        { group: "Our Media Partner", image: "/medpar39.png" },
        { group: "Our Media Partner", image: "/medpar40.png" },
        { group: "Our Media Partner", image: "/medpar41.png" },
        { group: "Our Media Partner", image: "/medpar42.png" },
        { group: "Our Media Partner", image: "/medpar43.png" },
        { group: "Our Media Partner", image: "/medpar44.png" },
        { group: "Our Media Partner", image: "/medpar45.png" },
        { group: "Our Media Partner", image: "/medpar46.png" },
        { group: "Our Media Partner", image: "/medpar47.png" },
      ],
    },
  ],
};
